<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "panduan".
 *
 * @property integer $id_panduan
 * @property string $judul
 * @property string $isi
 * @property string $gambar
 * @property string $aliasModel
 */
abstract class Panduan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'panduan';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul', 'isi', 'gambar'], 'required'],
            [['isi', 'gambar'], 'string'],
            [['judul'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_panduan' => 'Id Panduan',
            'judul' => 'Judul',
            'isi' => 'Isi',
            'gambar' => 'Gambar',
        ];
    }




}
